class Config_IRIS_FF:
    NAME_EXP = 'IRIS_FF'
    NUM_EXP_TO_RUN = 5
    EXP_INDEX_START = None

    NUM_EPOCHS_PHASE1 = 100
    NUM_EPOCHS_PHASE2 = 20000
    THRESHOLD_PHASE2 = 10 ** (-10)

    SHOW_PROGRESS = False

    NUM_TRACKED_DIRECTION_CHANGES = 1
    THRESHOLD_DEGS_DIRECTION_CHANGES = 0.1

class Config_MPG_FF:
    NAME_EXP = 'MPG_FF'
    NUM_EXP_TO_RUN = 10
    EXP_INDEX_START = None

    NUM_EPOCHS_PHASE1 = 100
    NUM_EPOCHS_PHASE2 = 30000
    THRESHOLD_PHASE2 = 10 ** (-10)

    SHOW_PROGRESS = False

    NUM_TRACKED_DIRECTION_CHANGES = 1
    THRESHOLD_DEGS_DIRECTION_CHANGES = 0.1

class Config_MNIST_CONV:
    NAME_EXP = 'MNIST_CONV'
    NUM_EXP_TO_RUN = 5
    EXP_INDEX_START = None

    NUM_EPOCHS_PHASE1 = 100
    NUM_EPOCHS_PHASE2 = 5000
    THRESHOLD_PHASE2 = 10 ** (-10)

    SHOW_PROGRESS = False

    NUM_TRACKED_DIRECTION_CHANGES = 1
    THRESHOLD_DEGS_DIRECTION_CHANGES = 0.1

class Config_MNIST_FF:
    NAME_EXP = 'MNIST_FF'
    NUM_EXP_TO_RUN = 5
    EXP_INDEX_START = None

    NUM_EPOCHS_PHASE1 = 100
    NUM_EPOCHS_PHASE2 = 10000
    THRESHOLD_PHASE2 = 10 ** (-10)

    SHOW_PROGRESS = False

    NUM_TRACKED_DIRECTION_CHANGES = 1
    THRESHOLD_DEGS_DIRECTION_CHANGES = 0.1

class Config_CIFAR10_CONV:
    NAME_EXP = 'CIFAR10_CONV'
    NUM_EXP_TO_RUN = 5
    EXP_INDEX_START = None

    NUM_EPOCHS_PHASE1 = 100
    NUM_EPOCHS_PHASE2 = 20000
    THRESHOLD_PHASE2 = 10 ** (-10)

    SHOW_PROGRESS = False

    NUM_TRACKED_DIRECTION_CHANGES = 1
    THRESHOLD_DEGS_DIRECTION_CHANGES = 0.1